---
abstract: >
    People serving indeterminate prison sentences in England & Wales progress largely based on assessments by officials of how well they have performed against the expectation to 'reduce their risk' of harming others in future. Prison scholars have noted that this kind of assessment prompts pains of 'tightness'. This paper draws on case studies of two life-sentenced men in an open prison, both contemplating the 'tight' conditions under which they might be released, and reflecting on their ethical lives in light of these. It describes the moral messages they received through punishment, and how they responded, ethically, to these. The paper argues that both men felt morally thwarted. For one, apparently impressive rehabilitative progress meant little because his licence conditions would make it impossible to fully pursue what he saw as as 'good' life; for the other, it felt impossible to mould himself to the complicated expectations risk management measures communicated. Both men were framing their ethical goals mainly in relation to the demands of their sentences rather than the lives they hoped to lead afterwards. This undermined one of the sentence's supposed aims, to reform and rehabilitate them and restore them to a position of qualified freedom.

affiliations:
  - id: cam
    name: University of Cambridge
    department: Institute of Criminology
    group: Prison Research Centre
    address: Sidgwick Avenue
    city: Cambridge
    region: Cambridgeshire
    postal-code: CB3 9DA
    country: United Kingdom
    url: https://www.prc.crim.cam.ac.uk/

author:
  - id: bj
    name:
      given: Ben
      family: Jarman
      literal: Ben Jarman
    email: ben@benjarman.uk
    orcid: 0000-0003-3527-5437
    url: https://benjarman.uk
    affiliation:
      - ref: cam
    acknowledgements: >
      Thanks are due to all participants in the Moral and Ethical Worlds of Confinement workshop held in Cambridge in July 2022, for the warm and constructive environment of the event; but I owe particular thanks to Alice Ievins, Anna Jordan, Ryan Williams, and Jago Wyssling for their comments on an early draft of this paper, presented there.

bibliography: jarmanPartFurnitureNow2022.bib
citeproc: true
csl: cambridge-university-press-author-date.csl
keywords: 
  - penal theory
  - moral communication
  - punishment
  - life imprisonment
  - murder
  - risk
  - risk governance
  - ethics
  - anthropology of ethics
  - moral thwarting
lang: en-GB
title: "“I'm part of the furniture now, innit?”"
subtitle: "Risk governance and moral thwarting among life-sentenced men in English prisons"
categories:
  - conference paper
toc: true
toc-depth: 2
draft: true
date: 2022-07-06
funding:
  statement: "The author received funding for this research via an UKRI PhD studentship, ESRC reference 2405252, co-funded by Quakers in Britain."
copyright: "© Ben Jarman, 2024"
license: All rights reserved.
description: Conference paper, delivered at a workshop in Cambridge in 2022.

citation:
  id: jarmanPartFurnitureNow2022
  abstract: >
    People serving indeterminate prison sentences in England & Wales progress largely based on assessments by officials of how well they have performed against the expectation to ‘reduce their risk’ of harming others in future. Prison scholars have noted that this kind of assessment prompts pains of ‘tightness’. This paper draws on case studies of two life-sentenced men in an open prison, both contemplating the ‘tight’ conditions under which they might be released, and reflecting on their ethical lives in light of these. It describes the moral messages they received through punishment, and how they responded, ethically, to these. The paper argues that both men felt morally thwarted. For one, apparently impressive rehabilitative progress meant little because his licence conditions would make it impossible to fully pursue what he saw as as ‘good’ life; for the other, it felt impossible to mould himself to the complicated expectations risk management measures communicated. Both men were framing their ethical goals mainly in relation to the demands of their sentences rather than the lives they hoped to lead afterwards. This undermined one of the sentence’s supposed aims, to reform and rehabilitate them and restore them to a position of qualified freedom.
  author:
    - family: Jarman
      given: Ben
  event-place: "Westminster College, Cambridge"
  event-title: Moral & Ethical Worlds of Confinement
  issued: 2022-07-06
  language: en-GB
  license: All rights reserved
  title: >
    "Part of the furniture now, innit?" Risk governance and moral thwarting among life-sentenced men in English prisons
  title-short: Part of the furniture now, innit?
  type: paper-conference
---

# Introduction

  > I haven’t made any progress… whether I go from B to C to D… to me, that’s not progress.[^fn4] I’m still in prison. When I go out, I will still be on licence[^fn5] and I’ll still be a prisoner. That’s the way I look at things […] Going from B to C to D, no-- I don’t think that’s progress. I just think that’s just the natural course of events.
  >
  > Grant

  > BJ: Your tariff was… what, ten years ago, eleven years ago now?
  >
  > Jeff: Eleven. I knew I’d go past, but I didn’t know I’d go past it this long […] I just kept thinking to myself, “how long have I got to do? How long am I going to be here for?” And then it was a year, another year, another year [and] I started thinking, “Pfffft… Part of the furniture now, innit?”[^fn9]

Grant and Jeff were both held in an open prison. Both aged around sixty and both convicted of murder many years before, Grant, who was nearing his ‘tariff’ date,[^fn2] had recently learned that prison staff were recommending that the Parole Board release him, reasoning that the risk of his harming others again was manageable. Jeff’s tariff, however, had long since passed, and his record of occasionally unpredictable behaviour in custody left the impression of a riskier release. Although Jeff felt like ‘part of the furniture’---a forgotten and unnoticed feature of a wider scene—official worries associated with his possible release meant he was in fact subject to more intense behaviour monitoring than many of his peers, though whether he was aware of this was less clear. He was eager for release but uncertain what could bring it about, while Grant, who was likely to be released soon, said he was ‘in no hurry’.

As Grant’s words suggest, both men had progressed well enough against official expectations that they were trusted in an open prison. Even so, both also shared the feeling that their ethical lives were thwarted by the sentence, <!--RW: I think this is a productive avenue for exploration. For the Special Issue (SI) keep in mind: what is the problem and what does the empirical study of ethics (your data) offer that we already don’t know? It feels to me that you need to place into focus early on some of the tensions that you unpack below.--> in that their efforts to ‘do the right thing’ over many years had still left them unable to realise the long-term intentions which really mattered to them. <!--AI: right, so this is the crucial tension you're exploring and this is what you mean by thwarting. It's something about living trapped between two different moral systems. I would be inclined to make a little more of this sentence, just becuase it seems to be so central. I then think you can thread this tension better through the 'theory' section that follows.-->

To explain this situation, it is first necessary to review recent anthropological scholarship for an account of how people strive to shape themselves into whom they need to become. Two theoretical strands in this literature are discussed, before the specifics of each empirical case are described in greater detail. A final, concluding section discusses how Jeff’s and Grant’s attempts to be ethical were frustrated by the way officialdom addressed them about ethics: by imposing quasi-universal moral obligations, which were difficult if not impossible for them to realise in practice.

# Virtue ethics in practice <!--RW: I wonder if it might be clearest to have some of these relevant developments threaded throughout your analysis. Other detail, especially around ethics as involving self-conscious relation to norms/codes/rules, may be better suited in your introduction to help set up the distinct ethical framing of your project. In reading this section I think it might be too easy for the uninitiated reader to the anth of ethics to get lost.-->

’Poststructuralist’ accounts of <!--AJ--> virtue ethics <!--As I understand it, virtue ethics takes root in a particular tradition in moral philosophy (of which there are a few major perspectives; Aristotelian being one of them), and I'm not certain that all work in the anthropology of morality could be characterized as virtue ethics research. You might clarify this a bit by stating that you are particularly interested in this type of work within moral anthropology.--> [cf. @faubionAnthropologyEthics2011; @faubionFoucaultGenealogyEthics2012; @laidlawSubjectVirtueAnthropology2013; @mahmoodPoliticsPietyIslamic2005; @mattinglyTwoVirtueEthics2012], look particularly to the work of the later <!--AJ--> Foucault <!--I didn't even realize that Foucault's work might be characterized as a type of virtue ethics, but I suppose you're right!--> [e.g. -@foucaultHistorySexualityVolume1988;  -@foucaultUsesPleasureHistory1986] for conceptual and theoretical foundations. In this view, ethics consists in striving to occupy a ‘subject position’. Subject positions are shaped by a range of influences, not simply systematic moral codes. Certainly, they respond to such codes, which in turn are promoted by various social institutions (e.g. schools, professions, prisons, organised religions). To the extent that moral codes are promoted by established institutions, they are structured by existing power relations. But ethical duties also arise from relationships—familial, occupational, kinship, etc.---meaning that to occupy a subject position is not simply to replicate a moral code, but rather to reflect on one’s duties, to evaluate oneself, and to choose how one might fulfil the duties consistent with a good life.

Ethics, on this view, is not about reproducing norms. Rather, it is a question of reflective *autopoiesis* or self-formation: it involves cultivating the virtues commensurate with fluent moral action. <!--AJ--> ‘Technologies of the self’ <!--If I remember correctly, these technologies of self are also usually rooted in moral codes.--> are the means to this end, and might include any practice enabling such reflection: reading, prayer, psychotherapy, physical exercise, or artistic creation could all qualify, as could more explicitly pedagogical relationships with moral <!--AJ--> exemplars <!--Robbins also discusses exemplars and might be a useful reference if you're looking to add one. His 2018 piece, 'Where in the world are values?' is one I explicitly remember but there might be others.--> : teachers, mentors, or another person recognised as already occupying a given subject position, and through whom one encounters virtues and values (e.g. compassion, excellence, wisdom), realised in the world. The key feature shared by technologies of the self is that they afford reflexivity and a change of perspective, <!--JW: [This is clearly different when thinkingabout people with dementia]--> thereby permitting the subject takes the self an object of thought and action.[^fn8]

<!--AJ--> Subject positions are neither immutable nor monolithic, even when moral codes appear to be <!--There is a triadic relationship here between moral codes, individual ethical reflexivity, and 'duties' that I think might be really important for your paper, and it might be worth it to point it out in your introduction. Although, I'll have to read on to see if this is something you rely on for your analysis, but it does seem to nicely illustrate the issues Grant and Jeff struggle with in your opening quotes.--> <!--JW: [The link to moral action is still unclear to me.]-->. Put simply, this is because "one's duties are one matter [but] one's values and the ideals to which one might aspire are often quite another" [@faubionAnthropologyEthics2011, p. 30]. Different people may appropriate and fulfil similar duties in different ways. On this view, autopoiesis mostly reproduces moral norms, with idiosyncratic but insubstantial differences of praxis. But occasionally, especially when a subject finds their existing moral resources ill-fitted to unfamiliar circumstances or an alien environment, ethical reflection points *away* from the reproduction of moral norms and towards moral innovation, such that previously authoritative duties are reframed or discarded as no longer relevant <!--JW: **Is ethics necessarily tied to morals?**--> [cf. @robbinsReproductionFreedomMorality2007]. Unaccustomed or unexpected circumstances might prompt crises or jolt subjects out of habitual patterns of activity, prompting more fundamental kinds of reevaluation [@zigonMoralBreakdownEthical2007]. <!--AI: This seems like a point at which it's worth hinting back to the tension you're identifying. -->

A separate strand of scholarship on virtue draws largely on Aristotelian ethics. <!--AI--> This ‘humanist’ strand [@mattinglyTwoVirtueEthics2012] is in some ways similar to its poststructuralist counterpart. Both doubt the universal applicability of *any* approach to moral reasoning. Both are therefore opposed to Kantian deontology, utilitarian consequentialism, or the notion of any ‘authoritative’ approaches to right action. Both strands, rather than seeking to answer how human beings ought to conduct themselves, instead observe how human beings reflect on and evaluate their actions.  --><!--AI: This sort of detail doesn't feel (to me at least) necessary to the point you're making about thwarting (both what it is and where it comes from). That needs to be your key focus, so keep the detail that helps you explain what you mean by that excellent excellent term, and trim the rest--> <!--RW: I’m lost here in the importance of these two strands that you identify for your overall project/argument. It seems a finer detail that is perhaps less important than the ideas around the intersection between power (governance) and moral tragedies (thwarting). -->

<!--AJ, on an earlier draft: This is great, but would be easier to digest if you split it into two or three sentences.-->  ‘Humanist’ approaches to virtue ethics emphasise not so much how ethical considerations are embedded in power relations and social structure, but rather the phenomenological character of ethics. Its account is more biographical and temporal, and emphasises the lived-forward-understood-backwards aspects of ethical life <!--JW: **beautiful**--> , which in turn highlights the role of fate and luck in ethical thinking, and the notion of ‘moral tragedy’: situations in which people strive for unattainable, opposed, flawed or incommensurable visions of the good. Where people possess imperfect knowledge, for example, they are often nevertheless forced to imagine alternative scenarios they might still have no choice between. Narrative is important to humanist accounts of virtue ethics, both because it helps construct retrospective accounts of meaning, but also because it can project the self into possible futures [@mattinglyEthicsImmanentTranscendence2018] <!--RW: Perhaps make explicit how Mattingly’s idea of tragedy contrasts to your exploration of moral thwarting. --> . Also important in such accounts of virtue are the notions of first- and second-order desire. First-order desires are the things one *actually* wants; second-order desires are the things, having reflected on one’s situation and on the kind of person one might need to become, one might *want to want* (or might *need* should foreseeable circumstances arise). Finally, humanist virtue ethics has given us the concept of the ethical  ‘ground project’ <!--JW: narrative long-term projects of care--> : an organising narrative often inextricably linked with personal identity, and usually framed as a stable, lasting, long-term project of care (for the self or for others).

What follows draws on both accounts of virtue ethics <!--AJ: This section was well done, I think -- you cover a lot of theory and literature succinctly. Here I think it might be helpful to know why you’ll draw on both accounts and to what end. As you well know, many of the approaches you summarize have their own intricacies and draw on a wide range of theoretical and philisophical material, not all of which align together. This might not matter much to some (or most) readers, but I think it might be useful to specify some of the things you find most helpful.--> <!--AI: and the different forms of thwarting which each account entails - the thwarting which occurs when there is tension between subject positions or when the subject position stops 'working', and the tension which occurs as a result of a tragedy. Is that right?--> <!--RW: How does imprisonment present a problem for ethics in your work? Refine further --> . Jeff and Grant, both censured to lifelong punishment, were both subject to demanding moral codes suggested by their punishment. The moral demands of retributivist censure (which emphasised their autonomy and accountability) were imperfectly compatible with the expectation that they should subjectivate themselves to a licence regime in which their dangerousness (and lack of ethical autonomy) would be taken for granted <!--RW: This is the source of contradiction and source of thwarting. Can you unpack a little for the reader?--> . These codes posed contradictory demands, but were also backed by ‘tight’ penal power which made compliance a precondition of release from prison and subsequent parole. <!--AI: Yes - another key source of the thwarting. I wonder if this could also go up front and if you could find a way talking about the traditions of virtue ethics which links it into this tension and how it creates thwarting-->

The following sections describe, in turn, how each man responded to some of these contradictions, and how each came to feel thwarted, because the life licence <!--AI: I think this is the first time you've mentioned explicitly that the licence is for life - since that's crucial, make it clearer from the beginning. It might even be making more of - it matters because it makes their projects impossible - they're made to work towards a future which they're also blocked from entering.--> either directly blocked what they understood themselves to be living *for*---their  ‘ground projects’---or made these projects appear confoundingly difficult to pursue, even to the extent that they might appear (to officials) unethical. <!--JW: This points to differing ethical demands of the institution. What are these? "You are supposed to change/redeem yourself. But not like this?" Well, how then? We might ask: What are the conditions under which prisoners can be the givers of care? How/When are they granted to be persons embedded socially? I'm thinking: perhaps there are moments where release is dependant on being able to show one's stable social surrounding. But perhaps in these moments where a kind of socially grounded idea of personhood is accepted by the institution, care is envisioned to flow in the direction of the prisoner-->

# Grant

As the epigrammatic quotation at the start of this paper makes clear, Grant insisted that he had made no progress in prison. But this was puzzling. Simply for him to be in an open prison *before* his tariff expired was unusual; his confidence in a fair chance of release at the first opportunity even more so. From a third-person perspective, <!--RW: According to institutional criteria? Explain for those unfamiliar with UK prisons… --> Grant had made *exceptional* progress in custody. Seen from the *inside*, however, Grant’s entire sentence was a story of unredeemed remorse.

Grant had killed his wife after learning she had been unfaithful. Describing memories of his career and (for many years) his happy marriage, Grant’s account of how things had gone so wrong took the form of a tragic narrative. He was at repeated pains to emphasise that he was fully responsible for the grave wrongs and harms caused by his lethal violence, and he worried about how his wife appeared in his telling of the story, but nonetheless maintained that both of them were responsible for the marriage having become toxic. This, he said, had been a delicate point to make in an offending behaviour course, which had been predicated on teaching Grant the ‘skills’ needed to better manage his emotions in (presumptively) “healthier” future relationships. While he had willingly participated in the course, Grant intended to completely pre-empt such a situation:

  > *If* I got into a relationship, then yeah, there’s a bloody increased risk. Course there is. And I understand where they’re coming from. And I respect that. But what they should be also respecting [is] that I’m not gonna get in a relationship. [I said this to them] and [the facilitator] said to me, “oh, don’t you trust women?” I said, “no, it’s not to do with that, it’s how I feel”. I said, “supposing I meet someone”, […] I said, “do I take her to the ballet, and then at half-time, over a gin and tonic, I say, ‘oh, by the way, I murdered my wife’?” It ain’t going to happen! It’s just not going to happen, you know? [five-second pause] Yes, it’s nice to have companionship, and that could be a problem later on.[five-second pause] But you don’t have to be lonely in this life [sighing] […] There’s no more lonelier place than in prison. And, I mean, I’ve got through [that].

As these words suggest, Grant found it difficult to look to a future which could *replicate* what he had lost, in which he could simply begin a new relationship but with the benefit of added ‘skills’. Rehabilitation could not *restore* him to a better life <!--AJ: I'm curious, are discourses related to "redemption" prevalent in English prison rehabilitation programs? It's a theme I've encountered here, mainly in activist circles (and rehab programs here often initiated by reformists). It implies this washing of sins, a blank slate, and full restoration. But the reality of things are quite different, of course. In any case, this made me think of that contradiction.--> <!--RW: See next comment-->. Instead, Grant found it more meaningful to occupy the subject position of a repentant, but morally accountable, ‘retributive subject’. <!--AI: So in part he wants to look to the past?--> <!--JW: repentant but morally accountable--> Grant accepted that he *could* be risky, not that he *would* be. <!--AI--> Instead of working to internalise the idea that he was dangerous, and learning the ‘skills’ required to manage this risk, he emphasised moral agency, responsibility, remorse, and repentance <!--BJ: move these references to footnotes and say these provide clear accounts of what these tricky and religiously loaded terms might mean--> [see, for example, @bottomsPenalCensureRepentance2019; @murphyRepentanceMercyCommunicative2011; @tasioulasPunishmentRepentance2006; @tasioulasRepentanceLiberalState2007]. <!--RW: I wonder if some of this literature might help frame the problem for your paper earlier on? There is clearly a contradiction you see between the responsibility intended and inculcation of moral agency and people’s actual mora/ethical experiences. The tension will become clearer here if it is unpacked earlier. --><!--AI(?): Right - different and conflicting moral demands are made on him - by his past and by the prison - and this is what causes the thwarting--> How important this had become to him was especially clear in his account of an interaction with a key member of staff:

  > I had a new offender manager.[^fn1] This is nearly three years ago […] Twenty minutes [into our first meeting], he said he was a great believer in fate. And he said it wouldn’t have mattered who I married, he believes I would have killed them […] He doesn’t know the background because […] it never came out in court. It wasn’t allowed to. So he’s just going on the records. Which I understand he’s got to do. That’s his job. I understand that. I’m not knocking that. But his personal thoughts and his personal beliefs about fate, <!--RW: Interesting, fate it is being framed as an individual belief but I wonder if this moral outlook, as being framed in a professional capacity, is shaped by or reflective of a wider institutional capacity? The institution and its risk management seems to operate under a shared understanding of fate or determinism. --> I think he should have kept to himself […] So… afterwards, I said to him, I said, “the courses that I’ve done and, like, the bereavement things I’ve done… about changing my beliefs, adapting them, dropping my beliefs completely…” I said, “isn’t it about time you looked at your beliefs?” And he went silent. He just did not know what to say. Because I think he felt that maybe I was right. And then his attitude changed towards me and we got on great guns,[^fn7] and we have ever since. I mean, he really has tried to help me. <!--JW: Wow! Nice analysis by Grant: Suggests that information which was not available does not matter to the offender manager. The logic of this particular documentation shapes the available subject positions.-->

Offender managers (henceforth ‘OMs’) have a key voice in the release process, through their written recommendations to parole panels [which are usually followed; see @bradfordDecisionmakingProcessParole2012a; @dykeHowParoleBoard2020a; @lackenbyParoleNotParole2018a; @powerReleaseNotRelease2018a]. For Grant to challenge his OM so starkly in a first meeting potentially jeopardised this important relationship, but can  also be seen as a ‘costly signal’ of Grant’s being (ethically speaking) the ‘real deal’ [on costly signals in biology and criminology, see, variously, @bushwaySignalingPerspectiveEmploymentBased2012; @gambettaCodesUnderworldHow2011; @marunaElementsSuccessfulDesistance2012; @zahaviHandicapPrincipleMissing1997]. In effect, Grant was demanding the OM recognise him as a responsible, ethical person, not misrecognise him as a ‘bad’ person or a risk. He did this not by questioning the legitimacy of risk assessment but by pointing to his accomplishments in a different moral register. <!--RW [referring to the previous sentence]: Unclear--> <!--AI: In the final article, and without going into loads of detail, you will need to talk explicitly about the risk assessment's ethical subjectivation. This might be something you could do in an amended theory section--> His reference of a privileged understanding of the background to his crime (“it never came out in court”) is also striking. It hints that he had *reasons* to act as he did. <!--AI-->Admittedly, these were reasons he now recognised to be mistaken, bad, wrong, even unacceptable; and he wanted it known that he had renounced them. Nevertheless, in referring to them his narrative sought to remind me that by taking responsibility for a shameful act and dissociating himself from the beliefs that led him to it, he had done the right thing. This was the basis for Grant’s turning of the tables on his OM, and his demand for recognition on his own terms. <!--RW: So doing right is important for moral capacity and this is unacknowledged and source of incapacitating moral potentiality? -->

Unlike technocratic classifications, interpersonal interactions can become ethically charged by questions of mutual regard [@keaneEthicalLifeIts2016, chap. 2] <!--JW: And also by pointing out the limitations of the Others ethical affordances. By pointing out the limitations of the Others perspective he acknowledges the Other's subject position. This seems like a beautiful entry into a relationship. Or: this is an elegant way of making the OM acknowledge Grant's subject position.******--> . That is to say, they entail the potential for second-person (or I-thou) rather than third-person (or I-it) relationships [cf. @lieblingDescriptionEdgeIIt2015]. For Grant, being visibly repentant was the ethical ‘ground project’: it had become so important to who he thought he was that he might “not know [himself]” without it [@mattinglyMoralLaboratoriesFamily2014, p. 12]. <!--AI--> It arose from his understanding of censure: <!--You will need to either go into this or rephrase it so it's easier for people who don't know penal theory to follow - something like 'It arose from his understanding of his punishment and what it demanded of him - a response and not merely passive acceptance'.--> that it was communicative, rather than merely expressive, calling for a response, not merely passive acceptance [see, variously, @brownleeOffenderPartDialogue2011; @duffOffendersCitizens2020; @duffPenancePunishmentLimits2003; @duffPunishmentCommunicationCommunity2003; @duffRetributivePunishmentIdeals1991]. Hence when Grant’s OM typified him according to a managerial logic which erased his sense of a *developing* moral character, and instead reduced him to a flatly risky other, Grant could not remain silent. From a subject position influenced by retributive, censuring forms of moral communication, he gave an account of his moral worth.

<!--AI--> Grant's response to censure might have involved expressions of remorse or regret, attempts at redress, or (where these are ignored, or impossible) the imbuing of future actions with some kind of redemptive meaning. All of these have been documented among life-sentenced prisoners in his position, albeit mostly those convicted when younger <!--Right - temporality again! The burdens of our past shape how we imagine our future--> [cf. @creweLifeImprisonmentYoung2020, chap. 7; @herbertOutsideExpandingNarratives2018; @herbertTooEasyKeep2019, chaps 2–4; @irwinLifersSeekingRedemption2009, chap. 5]. Yet the temporality of Grant's sentence---the fact that it came *after* he had, and lost, a family---left him struggling to imagine a new start. His daily life was replete with practices of penance, but struggled to accommodate practices of hope. He said his years in prison had been 'too easy', and he had, at times deliberately induced bodily suffering by declining to take essential medication. Grant also emphasised a penitent readiness to accept the imposition of lowered moral status. It appeared an ethical practice for him to try and fit his desires to the constraints of his situation, because *this was what he deserved*: <!--AI: Including the moral constraints? Because this will be another source of thwarting, right?--> <!--BJ: Also consider how to work in the idea of second-order desire, by pointing to the clearly ethical nature of what he's doing here (acting on what he wants)--> <!--RW: How much of Grant’s experience is about his specific crime and how much is about more general managerial risk management frameworks? Using Grant as an example is tricky because his crime is so specific, and difficult to frame even within the rehabilitation literature where family ties etc. are important. -->

  > <!--AJ--> All the way through my sentence, I've always had so many different offender managers, you know. And I've heard so many stories [from other prisoners] about exactly what's just happened to me. They [OMs] leave [their jobs] just before your parole hearing then a new one replaces them [and they don't recommend release]. Well, that's part and parcel.[^fn12] […] It has been said to me by OMU[^fn11] and my OM… "You know, Grant, you don't keep badgering[^fn13] us over things, you just get on with it." And that's true. I just do. If I get a home leave, fantastic. If I don't, I go to work [laughs].  <!--This almost reminds me of religious sects where deprivation is considered a moral practice.-->

While complaints about short-staffing in the OMU and administrative logjams were common in the open prison where Grant was held, he explicitly forswore “pushing” his needs to the front of the queue by chasing them up. Where others campaigned for home leaves by “manipulating the system” (Grant’s own evaluative description), his own ethical practices involved dutiful acceptance of whatever fate might send him. In part, this was because he felt so disconnected from the single thing that mattered to him the most, and decisions about his release therefore felt less important. Grant lived to be reconciled with his children:

  > G: I’m not one of those prisoners who is fighting to get out.  I was going to say I wasn’t fussed about getting out. That’s not quite true. But I’m in no hurry, then […]
  >
  > BJ: What if your children were in the picture?
  >
  > G: If my children was in my life, then I would want to be out yesterday. […] Let’s say I do get out on this first parole […] I’m getting out still without my kids in my life. So, yes, I can get on with my life. But what I want is my children in my life. To make it worthwhile, let’s say. So the prison’s priorities and my priorities will never match. <!--JW: different logics of what constitutes a person: Grant argues for a perspective that allows for relations to be an integral part of who he is. His kids in the future and the relationship to his wife in the past. The prison system seems to try to isolate an autonomous individual subject: Solely responsible in the past and self-dependant in the future.-->

However, measures in place to manage Grant’s risk of harming others meant this option was simply not open to him to pursue:

  > Without my children, I feel empty [fifteen-second pause, begins to cry]  Now, I haven’t heard from my children for [a long time]. I don’t know where they live. I don’t know if they’re married. I don’t know if they’ve got children. I haven’t got a Scooby.[^fn6] But I’ve got that little bit of hope […] If I was to hear tomorrow that-- If I got a letter, saying, “we never want to see you, you horrible bastard” [sobbing] then I’d have nothing. I wouldn’t care about work. I wouldn’t care about getting out […] When I had my risk board,[^fn3] the governor, she said to me […] “you can’t try and contact these names”. And two of the names were my children. And she said, “is that an issue?” I went, “yeah, of course it’s a bloody issue, but it’s not a problem” […] I’m not going to break the rules to satisfy myself […] I’m not going to break those licence conditions and then try and contact them. But it’s still a bloody issue.

<!--AJ and AI--> Risk management measures presuppose Grant to be at least potentially dangerous, such that he requires lifelong supervision and control. The possibility that he might actually be who he claims to be---a morally accountable and potentially trustworthy actor, and free to pursue his own visions of a good life---is discounted. Risk management <!--RW: I think this term serves as too much of a stand-in for close and careful analytical work that needs doing and showing. -->, as a relation of power, preordained the *telos* Grant might permissibly work towards: the absence of harm to others. What mattered to him and what he considered to be important, ultimately mattered only to the extent that it was compatible with a moral duty to make no unwarranted demands on others, and to become the means to their safety, security, and freedom from harm. <!--BJ: I think this bit needs some tightening. The key issue is that the game that's being played here has zero-sum outcomes, and that Grant is on the zero side whatever happens. The rules preclude even the exploration of circumstances in which a win-win might come about, at least to the extent that he might initiate it.--> Ultimately, then, risk management requires a good life for Grant (as the recipient of lifelong punishment) to be subordinate to that of his children, unless they take the initiative in contacting him. To the extent that he might try to realise his view of a good life, it was unlikely to be read as such, but instead as evidence of risk. <!--RW: Same as above -- it’s easy to fall into this common descriptive language but it erases some of the finer points that you want to make. --> <!--AJ: Let me see if I'm understanding this. To Grant, living a good life would mean reconnecting with his children. But according to risk management procedures, living a good life entails not contacting his children. I think where I get mixed up is that Grant also subscribes to retributivist models because he thinks he deserves to be punished (i.e., he cannot be redeemed), which in a way, to me at least, seems to align with risk management. If that's the case, does Grant believe he is (rightfully) precluded from moral possibilities (i.e., pursuing a "good" life)? --> <!--AI: This, to me, feels crystal clear and crucial--> <!--JW: Very nicely put!-->

It was in this sense that Grant felt thwarted, and unable fully to realise the selfhood he most prized. His subject position was that of a penitent, fitted best to the carceral half-world of the prison, but prepared to adapt himself to the thin and partial version of rehabilitation on offer to him beyond its walls <!--BJ: consider saying why he was willing to make this compromise: because of shame-->. <!--AJ [on an earlier draft]: This paragraph clarified for me the things I mention in the above comment. Perhaps I got tripped up on the organization of that previous paragraph (or it could just be me).--> <!--RW: Ok, on Grant, I think there is a lot going on with him in terms of analysis and themes that need unpacking or focusing. (1) there’s an overlap between crime, narrative of restoration, and managerialism (risk); (2) there’s a temporality dimension where the present-past-future are collapsed that contribute to the thwarting (what future does he hold given his past actions?); and (3) a difference between a high moral self e.g. where he might be able to have his kids in his life, and low moral self (revised expectations of how he might be able to live his life). -->

# Jeff

Jeff’s progression to open prison had been slower and more circuitous than Grant’s. Like Grant, he emphasised his remorse over his offence, and also that he deserved punishment. While he expressed frustrations about having served nearly one-and-a-half times his tariff (see below), he often qualified these, as the following two quotes should make clear:

  > I’ve taken somebody’s life, yes, and [they’re] trying to make me stay in prison for the rest of my life. So maybe I’ll just die in prison and not see the outside again.

  > I’ve deserved every single day of it. Every single day.

It had taken Jeff some years to fully acknowledge the gravity of his responsibility for having raped and killed a stranger in their home. Although he had handed himself in to the police, his guilty plea was not accepted, because by initially denying the rape he seemed to take a less-than-complete form of responsibility. He had been convicted by a jury and received a very long tariff by the standards of the time. His early prison experiences hinted at one source of the stigma he feared:

  > The staff used to [point prisoners out and] tell people, “oh, he’s a sex offender, he’s in for killing a kid, he’s in for this, that, the other”. Then they’d walk off and you’d get beat up and all that, yes? […] People [used to be] scalded, cut […] One of the lads I used to knock about with, he hung himself in his cell.

His change of stance came about because a full admission of guilt was a precondition of participation in an offending behaviour course which Jeff understood to be a prerequisite for sentence progression. Jeff’s description of the course was revealing:

  > J: You had to do roleplays of what happened.
  > BJ: What was that like?
  > J: It does your head in[^fn10] […] Because you have to play your victim, yes? To see how they felt, what they were going through, yes? […] Then you have to be you again, with somebody else as your victim. It’s not very nice, you know? Well, obviously, it makes you realise, you know, what they were going through, and I think that’s what they did it for.
  > BJ: Yes. Do you think that’s a legitimate thing to do with people?
  > J: I don’t know. I think if you’re strong, maybe, but some people aren’t that strong, are they? […]
  > BJ: Mmm. Did you feel strong?
  > J: I felt I’ve got to do it, innit? So I needed to understand where I went wrong and that, in my life, you know, what led up to it and that. So yes.

The reference to ‘strength’ here is significant, as is the whiff of moral coercion—Jeff’s feeling that he had “got to do it”. <!--RW: unclear--><!--AI: Make this a bit clearer - is the point that this experience in courses was painful but it was both something that he was compelled to go through by coercion or instrumentalisation, but also morally compelled to go through?--> <!--[and separately: Oh, reading what is below I think my comment above is wrong. I think you mean that it implies the former - that he had to 'go through it', to endure it, but not experience it. But I think this quotation could be read both ways - as experiencing punishment as expression or communication - which is a bit of a problem. I also think you need to work out whether adding the moral communication/expression literature is necessary here, or whether you can make the point you want to make without going too deeply into it. I guess I worry a bit that there's a lot of concepts/theory  - virtue ethics, subjectivation, different forms of moral communication - for people to get around and it makes it a little dense at times. Another option, I guess, would be to explore the moral communication stuff somewhere else, perhaps in the beginning when you lay out what the conditions were that create the thwarting--> Both suggest an understanding of moral censure as expressive, not communicative:

  > [C]ommunication involves, as expression need not, a reciprocal and rational engagement. Expression requires only one who expresses. If there [**is**] someone at whom it is directed, that person need figure only as its passive object or recipient […] Communication thus addresses the other as a rational agent, whereas expression need not. [@duffPunishmentCommunicationCommunity2003, p. 79–80]

For Jeff, retributive ethics posited ‘hard treatment’ [see @matraversDuffHardTreatment2011] as something to be endured, not responded to. Jeff’s “understanding” of his offence, referred to below, came in the form of received wisdom, <!--AI--> imparted through binary categories <!--unclear-->:

  > They made me understand things, like the course and making me understand the different ways about my life when I was outside, where I went wrong, pinpointed everything out for me […] I didn’t care about things, you know? I liked to have a drink, I liked money. Obviously I didn’t care about people, which I do now, because I used to rob people’s houses and take their cars and now I know that’s wrong.

Jeff’s description of his risk-related licence conditions was similarly passive, again suggesting compliance prompted by ‘dull compulsion’ [@carrabinePrisonRiotsSocial2005] not ethical subjectivation <!--BJ: Losing the way a bit here.--> <!--JW: I find this sentence scary: Considering the danger of becoming complicit with repression as a researcher, this sentence might be read by someone working in risk management as an assessment: "He doesn't really comply." If so, are you offering a refinement of the move away from punishment of the body and on to punishment of the soul described by Foucault?--> . Nevertheless, Jeff did not agree with all of the conditions proposed for his license. Risk assessors’ classification of Jeff’s elderly parents as ‘vulnerable’ made his visiting them at home into a potential safeguarding issue. This jeopardised the hope <!--RW: hope may not be the right word here as you haven’t developed the idea in relation to moral thwarting (but see my comment about time above). Perhaps this can be framed in terms of ethics as interpersonal and social. Does this point to an assumption of the institution that ethics is individualist, naively and neo-liberally so? A wider point here is to allow your cases to speak to the texture and assumptions of governance for the ethical subject. What does moral thwarting tell us about the way that institutions hold power over people and what does it allow power to achieve? --> that mattered most to Jeff, which was that he would be released in time to live nearby and care for them. <!--JW: again: social aspect of personhood denied.--> Yet he felt obligated to reciprocate their unstinting support ever since his crime:

  > You know, you say things to [the prison], like, “Oh, they’re ill,” and this, that and the other, and “they haven’t got that long left”. I don’t think they believe, you know? They don’t really know what’s going on. It will cause problems if they say to me I can’t see them […] Obviously, I know I’m going to be on life licence, so, obviously I know I need to get a job and get my own place and settle down, but I’ve got a family as well […] To distance me from them is not going to give me any support, is it? <!--JW: Does he make use of particular logic (perhaps social worker's?) as an ethical affordance (Keane)? Are there conflicting ethics of social work and the larger penal system?-->

However, in light of the role intoxication had played in his offence, and his history of sporadic substance misuse in prison, Jeff’s release was assessed to pose a ‘high’ risk of serious harm to the public, and as such would require tighter restrictions. Jeff saw these as unwarranted, but unlike Grant had learned not to offer a challenge. He found it difficult to explain this stance to his family:

  > J: I told my mum, yes. She wasn’t very happy. I didn’t want to worry her […] Saying, “Oh, when I come out, I might not be able to see the kids and I’ve got to have permission to see you.” She’s going, “Why? Why? Why? What’s…?” and then she said that again: “You need to stand up for yourself. Tell them, innit.”
  > BJ: Yes. What would happen if you did [stand up to them]? Let’s say, in your next parole board--
  > R: […] I’d probably say to them-- Obviously, you can only keep saying sorry and explaining what happened […] so much, yes? I’d say, “You’ve got all these licence conditions that you want me to do.” Because to me, yes, with all those licence conditions-- They put those licence conditions on it, I think, mostly because some of them are hard [and they want you] to fail, yes? So if you go out there and you don’t fail, yes, then they’re wrong, aren’t they? That’s what I’m saying. So, yes, pull me out of here, release me to prove you wrong. <!--JW: Interesting adaptation in order to be able to fulfill a requirement that one does not agree with!-->

It is significant that when Jeff was challenged by his mother to <!--AJ--> “stand up for himself” <!--I also think "standing up for himself" is reflected in his imagining that he'll comply with all license conditions and "prove them wrong."--> , he understands this to raise retributive questions—whether he has “said sorry” enough, or been punished enough—rather than questions about measures necessary to manage his risk. <!--AI--> In part, this was because he found the risk-based requirements so confusing that the best course of action appeared to be to delegate the substantive ethical work of self-representation in relation to them to a third party <!--But it's also because his sentence is imposing two ethical demands on him - to become a particular type of person who is 'safe' (future focused, risk-informed), and to be punished and repentant for his past (past focused, retributively informed). This might be a point you are about to make--> :

  > There’s no point disagreeing with it. Not me, anyway. I let my solicitor deal with it because he’s more clued up and he knows about all the laws and that, yes? To me, it’s more confusing than anything. You know, it’s just confused me. It’s just confusing to me. <!--AJ: Reading thus far, it seems to me that both Grant and Jeff have similar reasons for "giving up" so to speak, as a result of these risk evaluations and procedures, but they are expressed differently. For Grant, there's no hurry to get out if he is disallowed from reconciling with his children, despite being a "model" prisoner. For Jeff, he doesn't strive to be a model prisoner because he has already done everything he can (expressing remorse) and there's really no point if he won't be able to care for his parents.--> <!--RW: What is happening here? This is really complex and it needs unpacking and/or being threaded back together with your argument about moral thwarting. Perhaps it is a consequence of the form of power exercised that agency becomes dislocated from the subject to the bureaucracy deforming the placement of ethics as self-reform and turning it instead to points scoring against the institution…-->

Jeff understood compliance narrowly, and treated the license as a set of external impositions (“conditions you want me to do”, above). <!--AI--> He believed his duty was to accept censure and endure hard treatment, not to subjectivate himself to a more exacting (and ambiguous) set of demands he hardly understood. This, and ‘outsourcing’ ethical accountability to his solicitor, arguably made him appear *more* risky, in that he appeared unable even to self-govern. <!--JW: As with the scary sentence above: I am unsure whether this sentence constitutes a risk assessment of your own. Do you want to assess his risk?--> If so, this would jeopardise the project that most engaged his hopes—getting out of prison to care for his parents <!--Right - this is about impossibility of the demands placed on him, right? 'It's not enough for you to do what we say, we demand that you want to do what we say.' This demand for desire is what causes the thwarting - his moral preoccupation is something else and he can't pretend his moral project is his rehabilitation, but not convincing people that his moral project is rehabilitation means he can't realise his real project. Here the thwarting is because of the impossible and exacting demands of the institution--> . He found it hard to imagine how he would carry on if they died before his release:

  > When I read things like that in my parole [papers] [i.e. licence conditions obstructing contact with his family], I think, “is it worth me getting out? Is my life… you know, well… why?

Jeff’s implicit claim—that he had responded appropriately to retributive punishment by receiving ‘enough’ pain—was similar to Grant’s. However, it was also less successful, in that it was less likely to be recognised as a coherent ethical presentation, and (in its passivity) was less compatible with the ‘tight’ expectations of penal power [see @creweDepthWeightTightness2011; @creweTightnessRecognitionPenal2021; @rennieTightnessAutonomyRelease2022] <!--JW: Demanding coherence resonates a lot with my observations.--> . Jeff’s offence and his patchy compliance record meant that risk assessors were bound to exercise caution; but this only increased the importance that Jeff perform fluently in the role of the reformed penal subject.

There are serious questions over the fairness of Jeff’s situation, mostly relating to his difficulties with understanding what was expected of him. Jeff’s prison records recorded his difficulties in various ways. One report in his files stated that he “[met] the criteria for mild intellectual disability”; another recorded that he had “antisocial personality problems, untreatable”, and was “bordering on psychopathic”. Each assessment, however technically valid, implied different moral evaluations <!--RW: Break apart the two aspects here: 1. The moral framing/implications by the institution, Moral judgements reflect the moral world (‘thinking’) of the institution. 2. How Jeff’s own ethical subjectivity was effected. -->. Jeff could appear needy and confused, or uncontrolled, manipulative and dangerous, depending on the framework of understanding applied to him.

In any case, from the perspective of risk assessment he was not autonomous but dependent, and not trustworthy but risky, a classification which reproduced itself. The nearly thirty separate risk factors listed in his proposed licence conditions attested to the enormous range of ways in which might fall foul of his licence. <!--JW: Which kind of proves him right: He is set up to fail.-->  Yet a retributivist understanding of Jeff’s conviction (including his own) would be that he *had* done wrong and *was* accountable. Challenged to account for himself, he gave reasons for his behaviour. But these were simplistic, and risk assessors responded by intensifying surveillance and monitoring, as though his behaviour were caused and pathological, not reasoned and ethically errant. Jeff’s response was confusion. <!--AI: Right - the tension between the two forms of accountability which the system relies on are crucial, and he's caught in the middle--><!--RW: There’s a mismatch to be sure, but there’s quite a lot going on in both examples and each quote that you need to draw your reader back to the flow of the argument and the main point about what ethics offers these otherwise familiar tensions (e.g. risk versus selfhood). -->

# Conclusion: risk-driven punishment as an incapacitative ‘morality system’

Incapacitative rationales imply certain presumptions about the moral status of the person being punished and the obligations to be expected from them. First, lifelong surveillance and control measures imply a presumption of permanently elevated risk. Second, lifelong supervision and permanently diminished civil rights imply a presumption of permanently lowered social status. Third, the life-sentenced prisoner on licence is presumed less competent in the art of ethical deliberation, with their ethical aspirations and hopes seeming to coexist with those of others only in a zero-sum relationship <!--JW: I find this interesting! On one hand, yes: There are not deemed ethically competent. On the other hand -- as Jeff’s story illustrates nicely -- the are expected to come to predefined conclusions on their own. I am reminded of fights I had in early intimate relationships: “I want you to** **want** **to do …!”--> . Fourth, if the ethical aspirations of the person being punished differ from the welfare or interests of others, the relationship is presumed to be zero-sum unless proven otherwise, meaning that the realisation of these aspirations must be <!--AI--> thwarted <!--Interesting - this is thwarting as a strategy of power, rather than thwarting as a by-product. Both are extremely interesting, but I think you need to be clear about which you're arguing for-->.

Ethically, all of this recalls the philosopher Bernard Williams’s description of how ethical considerations congeal into “morality systems” [@chappellBernardWilliams2018; @williamsMoralityPeculiarInstitution2011]. For Williams, ethical considerations apply *contingently*. The norms envisaged by moral codes might be wide in scope, but balancing them out and applying them in practice is a matter for deliberation by particular persons situated in contingent contexts. The resonance with the poststructuralist account of moral codes and subject positions should be clear; so too the temporal themes of imperfect knowledge and moral tragedy in Jeff’s and Grant’s accounts recall the humanist focus on first-person ethics. <!--BJ: This final sentence could go.-->

<!--AJ--> Since the Enlightenment, Williams argued, there has been an increasing tendency to treat ethical considerations as though they are prompted, always and everywhere, by *moral obligations* of a more universal character: <!--I wonder if the literature by Williams might be better served in your theoretical overview section. I think it helps to contextualize the contrast you're trying to make between the morality of the "system" and moral subjectivities of Grant and Jeff. -->

  > [T]here is a pressure within the morality system to represent every consideration that goes into a deliberation and yields a particular obligation as being itself a general obligation; so if I am *now* under an obligation to do something that would be for the best, this will be because I have some *general* obligation, perhaps among others, to do what is for the best. [@williamsMoralityPeculiarInstitution2011, p. 175, emphasis added]

Untethered from temporal and biographical context, obligations proliferate and become overriding, general and inescapable. Moreover, obligations must always be reconcilable, otherwise they are not obligations. It follows that they must *all* be accomplished; if not, either the deliberation was faulty, or the actor was simply immoral. As Williams made clear, this makes “blame [the] characteristic reaction of the morality system”, and “remorse or self-reproach or guilt […] [its] characteristic first-person reaction”. Without experiencing these, individual persons “would not belong to the morality system or be a full moral agent in its terms”. Put simply, there is no escape from blame:

  > “moral judgment and blame can apply [even to those who] want to live outside that system altogether. From the perspective of morality, there is nowhere outside the system, or at least nowhere for a responsible agent.”  [@williamsMoralityPeculiarInstitution2011, p. 177–8]

<!--AI--> Morality systems, then, make obligations categorical, so that they trump and sideline other considerations, even those which are undeniably ethical (in that they concern how a particular person can imagine and pursue their own idea of 'flourishing'). From this universalising position, considerations defined by what matters to a given person (in Grant's case, the possibility of reconciliation with his children, or in Jeff's case, the imperative to reciprocate his parents' care) are simply subjective---in the pejorative sense of being solipsistic and antisocial. They lack priority, compared to the apparent universal good secured by 'preventing harm'. <!--great-->

<!--BJ: could also critique further based on the paragraph above, in that 'no harm' is not a positive good, and in that prison does a lot to compromise wider security while also distributing the injustice and harm that do exist in the world very unevenly.-->

Jeff’s and Grant’s attempts to be ethical existed within a wider context where they were both blamed as if accountable and responsible, *and* controlled as if unaccountable and ‘dangerous’. Their moral status, therefore, was ‘overdetermined’ [see @altmanPunishmentTheoryMass2021]

  > Overdetermined actions fit neither into the temporality of backward-looking retribution—in which the punishment follows the crime—nor the temporality of forward-looking deterrence—in which future crimes can be prevented […] the specifics of an individual’s past actions and the open-endedness of their future actions are shouldered out by the assumption that they are essentially wrongdoers who pose a danger to […] innocent, lawful (typically white) citizens. [@altmanPunishmentTheoryMass2021, p. 14]

To Jeff and Grant, the norms of responsibility and blame suggested a commensurate ethical response of repentance <!--RW, on an earlier draft: Against some of my comments above, this seems to frame the tension well. Pull this clarity early up in the text to help frame the problem that punishment is presenting to ethics and what attention to empirical ethics is offering (namely, for your paper, moral thwarting). I wonder if the book called unfinished edited Biehl and Locke might be useful if haven’t already come across to see if there is something close in the anth literature that resonates with moral thwarting. Lucas Bessire’s chapter on negative becoming on, I think, Amazonian tribespeople, gets at the self-limiting (even harmful) legacy and colonialism/post-colonialism. It speaks to an internalized forms of power more than your paper but it shares an idea of the lack of moral progress. I’m also wondering why moral thwarting is a useful idea rather than speaking about ‘pain’ as is more common in prison sociology. It might be worth thinking through the difference there to find the value in foregrounding the empirical study of ethics.-->. What seemed appropriate to the subject position of an autonomous moral agent was to explore and declare the reasons for the offence, repudiate the beliefs and the selfhood that had produced them, and, in some sense, to think of themselves as ‘changed’.

On the other hand, their classification as ‘dangerous’ (to the extent that it left any space at all for moral agency) pitted their taken-for-granted self-interestedness against an abstracted notion of the general good enjoyed by others. It sought not their *reasons* for the crime, but an account of the *causes* which had produced it; and it sought this account so as to enlist them in the effort to govern risk. They could respond by coming to agree that they had acted under the influence of some ethically deranging influence (e.g. substance misuse, mental ill-health, cognitive disability, faulty thinking, etc.), and if so it followed that their autonomy and self-control were dilute or non-existent and could fail again. Or they could respond by dissenting and continuing to offer their reasons; but doing so would reveal them as incorrigible, or even as predators. In either case, their wrongdoing would be classified as caused, not as driven by (mistaken or disavowed) moral reasons.

In either case, the commensurate ethical response from the recipient of punishment was patient endurance, while officials strove to diagnose and treat pathology. The extent of compliance, the observed consistency of changed behaviour, and the subject’s responsiveness to incentives and disincentives, would all reveal whether they were rational agents capable of supervised self-governance, or incorrigible and dangerous beings warranting only fear and control; but the judgement could only be made from outside.

<!--AI--> As philosophers of punishment have argued---and as this paper shows empirically---the two views are hard to reconcile and the availability of each to be deployed in the event of a breach of obligations <!--BJ: examples --> makes balancing them out extremely difficult for the individual. <!-- Yes! The prison can use a different understanding of autonomy depending on what obligations it is trying to impose. I think there's a link as well between the different understandings of autonomy that the men themselves hold and whether their focus is forwards or backwards looking, but I can't quite get there.--> As Grant's retort to his OM suggests, moral recognition can be demanded from persons, but not from systems. The life-licensed prisoner has been constructed as a category of person who must self-govern without appearing to impinge on others, and who must live within the constraints of their lowered status. This formidably constrains ethical life. It is scarcely surprising that many life-sentenced prisoners espouse a more retributive worldview, even at the cost of trapping themselves in the past. 

<!--AI: Overall, I think this is excellent. I love love love the idea of thwarting, and I think it's important both to prison scholars and anthropologists of ethics. My main thought on the paper as it is is that it's a little dense. That's partly because of the compressed length, and I think making it 8000 words would help it breathe a bit, but it's also because it draws on a lot of knotty theory (different versions of virtue ethics, different versions of moral communication, different version of autonomy…). I think the main contribution you can make with this paper is to outline exactly what you mean by thwarting, and how does it come about? What is it about the experience of being a life-sentenced prisoner in England & Wales that thwarts people? I think you do answer that question in the article but you say so many other things that I don't think it comes through as clearly as it could. I think the reason will be partly to do with the system of power/governance operating on them, and it will partly be to do with the particular temporal burdens/limits of being an LTP (someone who carries a heavy heavy past, a delimited future (delimited by the licence but not just the licence), and lives a present shaped by a confused form of governance.) And it's also something to do with the two forms of autonomy (or the two forms of personhood?) that the institution can draw on in governing them, and the difficulty of situatiing themselves in relation to that--> 

<!--JW: This is ethics: choosing a retributive worldview to make sense of their situation. It traps them in the past, yes. But I wonder: What does it allow? What does this worldview free them from? Can it be only explained through the constraints?-->

# References

:::{refs}
:::

[^fn1]: An official tasked with assessing a prisoner’s risk of causing harm in future, and with formulating a plan to manage it.

[^fn2]: i.e. the end of the ‘minimum term’ to be served in custody, marking the end of the ‘penalty phase’ of a life sentence.

[^fn3]: A meeting at which the conditions surrounding Grant’s release, and the terms of his release licence, was discussed.

[^fn4]: ‘B-cat’, ‘C-cat’ and ‘D-cat’: security classifications for male prisoners in England and Wales. Category-A prisoners are held in maximum-security conditions. Category-D prisoners are held in ‘open’ prisons, involving the lowest degree of restrictions. Categories B and C are intermediate steps.

[^fn5]: ‘On licence’: subject to formal supervision requirements and control measures. These are imposed for life and non-compliance with them can prompt recall to custody.

[^fn6]: Rhyming slang: “Scooby[-Doo]” = “clue”. Hence, “I have absolutely no idea”.

[^fn7]: i.e. got on very well together, formed a very good relationship.

[^fn8]: Using different conceptual language, Webb Keane [@keaneEthicalLifeIts2016, p. 27–32] might describe technologies of the self as *ethical affordances*---features of a person’s environment which are real but not determinative of action,  and which solicit the subject’s attention as being useful in some way for ethical work.

[^fn9]: i.e. having become invisible or unnoticed, usually through lengthy occupation of a scene.

[^fn10]: “Does your head in” - is difficult to think about, is extremely unpleasant.

[^fn11]: OMU: the Offender Management Unit, the department in every prison which employs Offender Managers and which is responsible for risk assessment and sentence planning.

[^fn12]: ‘Part and parcel’ - “that’s an integral part of the situation”, “that’s just the way things are”

[^fn13]: ‘Badgering’: persistently and repeatedly asking the same question.