---
abstract: >
  In this lecture, Ben explores the myth and reality in how society responds to serious crimes, charting the uses and abuses of retributive punishment, rehabilitative intervention, public protection, and calls for incremental or radical reform. Drawing on personal and professional experiences, Ben will invite Friends to reflect on where current prison conditions belong in the longer flow of Quaker witness on penal reform, and to ask: who (if anyone) gets what they deserve from the institutions we have?
affiliations:
  - id: bbk
    name: "Birkbeck College"
    department: "Faculty of Humanities and Social Sciences"
    address: |
      "Malet Street"
      "Bloomsbury"
    city: London
    postal-code: "WC1E 7HX"
    country: "United Kingdom"
    url: "https://www.bbk.ac.uk"
  - id: icpr
    name: "Institute for Crime & Justice Policy Research"
    address: |
      "Malet Street"
      "Bloomsbury"
    city: London
    postal-code: "WC1E 7HX"
    country: "United Kingdom"
    url: "https://www.icpr.org.uk"
author:
  - id: bj
    affiliation:
      - ref: bbk
      - ref: icpr
    name: Ben Jarman
    email: "ben@benjarman.uk"
    orcid: "0000-0003-3527-5437"

title: Getting what we deserve?
subtitle: Imprisonment and the challenge of doing justice
funding:
  statement: "The author received funding for this research via an UKRI PhD studentship, ESRC reference 2405252, co-funded by Quakers in Britain."
keywords:  
  - long-term-imprisonment
  - punishment
  - quakerism
  - 2019 london bridge attack
lang: en-GB
date: 2024-07-27
description: Keynote lecture delivered at the 2024 annual meeting of British Quakers. 

url: https://www.youtube.com/watch?v=vwqolkC0nnc
title-block-banner: true
copyright: "© Ben Jarman, 2024"
license: CC-BY-NC-SA 4.0
toc: true # Will depend on whether it's a full text or a summary.
categories: lecture
# description: 

bibliography: jarmanGettingWhatWe2024.bib
csl: cambridge-university-press-author-date.csl
draft: true # remove after finishing.

citation:
  id: jarmanGettingWhatWe2024
  author:
    - family: Jarman
      given: Ben
  event-place: London
  event-title: Swarthmore Lecture, 2024
  genre: Lecture
  issued: 2024-07-27
  language: en-GB
  license: CC-BY-NC-SA
  publisher-place: London
  title: "Getting what we deserve? Imprisonment and the challenge of doing justice"
  title-short: Getting what we deserve?
  type: speech
  URL: https://www.youtube.com/watch?v=vwqolkC0nnc
---

# Background

This was the text of a keynote lecture given in July 2024 to the annual meeting of British Quakers, in London. The text below is the lecture as delivered. A publication expanding on it further will appear in 2025. The lecture can also be viewed online.

{{< video https://www.youtube.com/watch?v=vwqolkC0nnc >}}

***

# Introduction

Friends, today I’m going to discuss some big ideas: justice, punishment, rehabilitation, belonging, and what the American prison chaplain and sociologist Reuben Miller calls “the gift of proximity”.

Miller urges academic researchers to engage closely with individuals in the penal system. He warns against viewing people through the lens of abstractions like “rehabilitation”, or through policy metrics such as “reoffending”. Miller quotes the American death penalty lawyer Bryan Stevenson, who suggested that to understand the lives of others, we need to get close [@millerHalfwayHomeRace2021, loc. 22.7].

I want to share how the gift of proximity has changed what I know—making it more complicated, less certain, richer, and more real.

And I want to invite you to think about how you—how we, as Quakers—might also try to get close, to the system which acts on our behalf to respond to crimes. I also need to warn you, at the start, that some of what I will say may feel quite heavy.

# Three friends

Let me introduce you to three friends of mine. They were all released from prison in the past ten years, after serving long sentences for violent crimes. They received valuable help in prison, to address the harmful behaviours which put them there. None of them has gone back. None of them uses violence any more. “No more victims”, as the saying goes. In one sense, they represent success stories.

To protect their privacy, and that of others, I’ve changed many of the names I’ll use this evening. I’m going to call my friends Nelly, Lomana, and George.

### Nelly

Nelly has thrived since his release. In prison, he confronted the trauma of growing up around a violent, authoritarian father. He speaks of the therapy he did in prison with relief, crediting it for freeing him from a destructive cycle of thinking, which was not working for him, but which he couldn’t escape on his own.

After release, though his plans to set up a business faltered during the pandemic, Nelly still had secure accommodation, and he made the best possible use of contacts and services he’d engaged with in prison. He found a job, and now supports businesses to cast their nets wider and hire people he calls ‘diamonds in the rough’—people like him, who have been excluded in one way or another, but just need a break. He lives with his partner, is warmly integrated into a network of family and friends, and despite some health problems, he radiates gratitude and joy. I love catching up with him: he’s the kind of person who leaves you feeling warm inside.

### Lomana

Another friend, I’ll call Lomana. For now, he is doing well, but things are complicated. The complications come back to the fact that he arrived in this country as a child refugee. When they fled a war in their home country, his family became separated. For some years, Lomana and an older sibling lived alone in refugee camps. Years later, they were reunited with their parents, who had reached the UK. But unaccompanied children fleeing war zones are incredibly vulnerable. Lomana and his siblings suffered some terrible experiences, and arrived traumatised and lost. Struggling in school, Lomana joined a gang as a teenager, in which violence—both suffered and inflicted—became a way of life. Shortly after becoming a father, he received a long sentence.

In prison, therapy helped him come to terms with this trauma. But upon release, he faced a new challenge: citizenship. Nelly’s parents had been members of the Windrush generation; he was born here. However, Lomana, who’s much younger, wasn’t. He isn’t a UK citizen, and it’s long been our government’s policy to deport people who’ve done more than a year in prison back to their country of origin. ‘Foreign criminals’ is the language that they use to tidy away the human complexity behind this policy. Lomana’s leave to remain in the UK was revoked while he was in prison. Since his release, while his appeals play out, he has remained in a legal limbo. He can’t work. He can’t claim benefits. Somehow, he has found a kind of stability. He is a wonderful, dedicated dad, with a positivity I find inspirational. But he can’t yet rest easy. What he has worked towards might yet be snatched away.

### George

Finally, there’s George. George, too, suffered very deep-seated damage in childhood. His father maintained a violent, abusive reign of terror over George and his family. It only ended when George’s father went to prison for a very long time.

George’s unmanageable behaviour as a teenager led to school exclusion and, ultimately, to his being taken into care. He was often in trouble with the law. Countless interventions were offered, but didn’t get through. Sometimes, people who are hell-bent on taking a path will take it until they’re ready not to. George spiralled into chaos. He was eventually sent to prison after attacking and seriously hurting someone, in circumstances he still feels shame about today.

George’s psychological wounds are visible as self-harm scars. But he too went through therapy in prison, which instilled in George a desire to help others avoid his path. In prison, he discovered that education was his thing. He had an uncommon academic talent. When George was released, he was in a good place. He enrolled for an undergraduate degree, found a job, juggled these commitments and, for a time, seemed to be moving into a different life. He’s not back in prison, but things haven't haven't haven't been good for him. Later on, I’ll say more about one reason why this is so.

In all three cases, perhaps we can say that people ‘got what they deserved’: Nelly, Lomana, and George paid a penalty for breaking the law; the people they hurt saw them locked away in a place where this hurt could not be repeated; and the rest of us were protected by their harmful behaviour being interrupted.

But I want to suggest this evening that this isn’t the full story.

# Getting what we deserve?

One reason is that not everyone receives the benefits of therapy while they are in prison.

Nelly, Lomana, and George all served part of their sentences at Grendon prison, in Buckinghamshire. Grendon has a connection to the Swarthmore Lectures: in the year 2000, its then governor, Tim Newell, stood where I am standing today, and spoke partly about his work there. Men who go to Grendon are all serving long or life sentences, usually for killing or seriously harming others. And yet Grendon has always been, and is still, one of the safest prisons in the country [@hmchiefinspectorofprisonsReportUnannouncedInspection2023a]. Life there is organised around the daily delivery of group therapy. It is challenging. It is not a panacea: therapy only works for those who want to do it—not everyone does—and not everyone who wants to do it can hack it. But for those who do, it can be transformative.[^1]

The experiences of people who go to Grendon reminds us of something important: that people who do terrible things can and do turn their lives around. But Grendon, and therapy, are not the answer to everything that is wrong with the system as it is now. Even when people make the changes they need in prison, the world is outside prison can set them back on their heels again.

The UK imprisons a higher share of its population than any other Western European country [@HighestLowestPrison]. As our new prisons minister James Timpson has commented, many of those people should never have been sent there: short sentences, for relatively less serious offences, simply make it more likely that people will cycle out of prison, and back in again. A responsible government—and let’s hope we now have one—would reform sentencing to do something more effective with this group.

But this evening, most of what I have to say relates to a different group of people, people like those friends of mine, people who *have* done serious harm. Over the long term, the biggest factor driving our high use of imprisonment *isn’t* that we over-punish less serious offences. It’s that we over-punish *more* serious offences: we send people who do serious harm to prison for longer and longer [@ministryofjusticeStoryPrisonPopulation2020]. And then, if they work their way out of prison, we seem to find it more and more difficult to find places in which they can belong—or even to accept that they *should*. If, as Quakers, we want to be involved in the work of reconciliation, and to work where we can do the most good, then I want to suggest that it’s the most serious cases demand our attention.

People who serve long sentences are the group least likely to emerge from prison and harm others again. People who serve long sentences are much less likely to reoffend.

So this evening, I am going to try to point to a deeper story. It’s a story about the emotions that underpin punishment, and it’s also about exclusion, and about who belongs.

Whether prisons are punitive or rehabilitative, whether they function well or badly, whether they are English or Norwegian, and however well they protect the public—whatever you think of them, basically—they consistently do one thing: they divide people who belong from people who don’t. They enforce division. ‘We’, who are good, respond to actions by ‘them’, who are bad. The response is to create a separate world, *in there*, where *people like them* belong; *out here* is where *people like us* belong. To get back out here, they have to earn their redemption by conforming with our standards.

# Quakerism and penal reform

Shortly, I’m going to invite you to zoom in with me, and consider this big picture from close up. But beforehand, let’s ask how Quaker history might inform our approach to these issues of belonging.[^2]

As with our involvement in the movement to abolish slavery, we Quakers sometimes simplify the story of our involvement in penal reform. We tidy up complicated facts, to better fit our self-image as progressive people on the right side of history.

In this country, for example, we remember Elizabeth Fry, nicknamed “the angel of prisons”, as the driving force behind the 1823 Gaols Act. It mandated sex-segregated prisons to protect gaoled women from sexual exploitation. But we mention less often that many of those women still went on to be transported to penal colonies around the British Empire [@nellisQuakersPenalReform2013].

Similarly, it might shock us to learn that in the late 18th and early 19th centuries, Quakers in Pennsylvania pioneered the use of a technique we now recognise as a form of torture: solitary confinement [@odonnellPrisonersSolitudeTime2014; @crawfordiiiReportPenitentiariesUnited1834]. In trying to improve the conditions that existed then, they enforced the use of silent reflection, thinking that what worked for us would reform the criminal. Good intentions, and kindness blended with coercion: a dangerous mix.

And, again, we might raise an eyebrow, on reading the American Friends Service Committee’s 1971 report, *Struggle for Justice* [@afscStruggleJusticeReport1971], to notice that one of its most impassioned arguments is *against* the idea that rehabilitation should ever be a guiding principle for prisons.

All of these past Friends had good reasons for acting as they did. I’m not trying to summon a sense of useless collective guilt. But I do want to draw your attention to two things.

First: in this field, good intentions easily go awry. The history of penal reform is rich with cautionary tales, and unintended consequences. We have best been able to avoid these not when we’ve prescribed for others what will be good for them, from a position of power or influence, but when we’ve been involved, and up close, accompanying and supporting those most affected by punishment.

Second: there has never been a ‘natural’, settled Quaker position regarding the aims of punishment, nor how we as Friends should relate to them. Perhaps there should be. But it’s worth noticing that some Friends have worked *within* systems of punishment to humanise them. Others have worked with powerful people to try and shape policymaking [@loganPoliticsPenalReform2018]. Others have made major contributions to abolitionist thought and practice [@knoppInsteadPrisonsHandbook1976], or experimented with alternative measures like restorative justice [@nellisQuakersPenalReform2013]. Quaker history offers us many guides. But not all of these guides point us in the same direction.

With that said, I’m going to move from the big picture, to describing things I’ve seen very close up. I’m going to consider what serious cases look like, not when you read about them in the news or consider them as a policy question, but when you’re *involved*.

# Fishmongers Hall

When I described George, at the start, I left things hanging. I said:

> He enrolled for a degree course, found a job, and for a time, he juggled these commitments and seemed on the verge of moving into a different life.

George’s story, and those of many other people, took a turn for the dramatic in 2019. I said George found that education was his thing. That happened, partly, because of a project called *Learning Together*. It started in the Cambridge University Criminology department, where I was then a postgraduate student. It organised courses at Grendon, with students from Cambridge travelling to the prison for lectures and seminars alongside students from the prison. The project grew into a network: other universities formed other partnerships with other prisons. On that day, in November 2019, George and I joined over a hundred other people at a conference to celebrate five years of the project, in London, at Fishmongers Hall.

Many of you will remember the outline of what happened next from the news. Usman Khan, another former prisoner, was there too. He had worked with *Learning Together* in another prison, during a sentence imposed for offences under the Terrorism Act. He had been released around ten months before.[^3]

Usman Khan travelled to London carrying a bag containing kitchen knives, gaffer tape, and a fake suicide vest. During a break between sessions, he locked himself in a toilet cubicle, put on his vest, taped his knives to his hands, came out of the toilet, and began to stab people. Several bystanders confronted him, first inside the building and then on London Bridge. Using improvised weapons—a lectern, a fire extinguisher, and two ornamental narwhal tusks—they overpowered Usman Khan, and took away his knives. Within four minutes, armed police arrived and shot him dead. They weren’t asking questions about whether the vest carried a real bomb.

Two people he stabbed, Jack Merritt and Saskia Jones, lost their lives. Saskia was a friend of George’s. Jack was a friend of ours both.

I’m going to share just two memories from that day. One is of standing with George, a few hours later, smoking cigarettes in an underground car park, beneath the nearby building the police were using as a crisis centre. Having been separated from George and the others in the chaos of the building evacuation, I arrived there a couple of hours later, not knowing who had been hurt, how badly, or why. I just wanted to find my friends, and to know what had happened. But when I saw George, something told me that I *couldn’t* ask: it would be too hard to answer. And so we stood, together at least, in an underground car-park, chain-smoking, in the heaviest, most oppressive silence I’ve ever experienced.

The other memory is of seeing another person, who I will call Pete, performing an act of extraordinary compassion. Like some of those who confronted Usman Khan, Pete had served a very long sentence for a very serious offence. But what I remember is how kind, and how gentle, and how present he was, with someone else there in the crisis centre, who seemed to be in terrible shape: sitting on the floor, shirt stained with someone else’s blood, physically present, and utterly withdrawn. Later, through the inquests, I learned about the nightmarish situation this person had found himself in. I won’t describe it. But I will describe how Pete—this stigmatised man, this “dangerous” man, who had no particular reason to care about a person he had never met before sitting in distress on the floor. But there he was, sitting with him, getting him cups of tea, doing the work of being a little speck of light on a dark, dark day.

Just two memories. I have others. The second one, out of everything that happened that day, is the one I most care to remember. But it’s a crumb of comfort. It doesn’t bring back what was gone. Usman Khan stabbed five people. Two of them, and him, lost their lives. A colleague nearly lost hers. Hundreds of people—inside and outside prison—were left traumatised or bereft. There were personal and institutional aftershocks lasting years, and the *Learning Together* project is no more.

This violence was world-ending. Nothing could have prepared me for it. The losses have always seemed indescribable, and yet they have continued to evolve, and to demand reinterpretation and retelling, over the nearly five years since this happened.

Within the losses, though, have come gifts, opportunities, and consolations: the kind we find by encountering life not in a mediated way, not through headlines or statistics or abstractions, but *up close*. Up close, there are no labels. We are forced to pay attention, to see what is there in front of us: people who profess to have changed behaving abominably, and people we’re warned about offering pure humanity and compassion.

This is why proximity is a gift, and a privilege. It’s not always a comfortable one.

One thing I can say, coming from my proximity to this abhorrent act of violence, is that my attitudes have shifted. I don’t think we can understand ‘serious cases’ without taking seriously—and by this I mean, not dismissing or tidying away—the difficult emotions which underlie the urge to punish.

# Punishment

‘Punishment’.

It’s defined as the deliberate infliction of a loss on someone who is blamed for a wrong.

But what feelings does the word summon up in you? Do you, like me, think of emotions it’s better not to indulge? Do you think of anger, and hatred, and disgust? About payback, and the desire to make others suffer? These are unQuakerly words and feelings, aren’t they?

For a long time, I grappled with intense anger over various aspects of what happened at Fishmongers Hall. It consumed me, but since Usman Khan was no longer there to blame, my anger found other targets. I was angry about the media coverage, which dealt in the abstractions and clichés I’m trying to speak against tonight. I was angry about the inquest process, which dragged out forever, and seemed to assign blame where it wasn’t deserved. Most of all, I felt anger with the police, for killing Usman Khan on the bridge. Friends, I am not proud to admit this, but I wanted him alive, to take all the blame and to suffer in prison. This was magical thinking, and not even slightly reconciled to the situation as it actually was.

I am not the only Quaker to have noticed the importance of anger. Marian Partington’s [-@partingtonIfYouSit2016] extraordinary book, *If you sit very still*, describes how she came to terms with the disappearance and (as she found out over twenty years later) the murder of her sister Lucy by Frederick and Rosemary West. One of her themes is forgiveness. Marian Partington felt she ought to be able to forgive Rosemary West. But she found that these feelings of compassion were premature. She describes how, after initially resolving that she should forgive Rosemary West, her mind filled with anger and contempt. Eventually, more than ten years later, she wrote West a letter expressing feelings of sadness and kindness, but received in response only a letter from the prison, saying that West wished not to hear from her again [@partingtonIfYouSit2016, p. loc. 87.44-88.8%]. So: Partington’s book is about *opening* herself to anger and grief, experiencing these feelings fully, and finding that reconciliation and forgiveness have to be earned.

In a very different book, called *An ordinary murder*, the Quaker Lesley Moreland [-@morelandOrdinaryMurder2001] describes the aftermath of the murder of her daughter Ruth by an acquaintance called Andrew Steel in 1990. Much of Moreland’s anger related to the legal process, which asserted ownership over this most intimate of griefs. One example was that the police tried to prevent her from seeing Ruth’s body. Another was that she heard nothing directly from Andrew Steel during the trial, only what she calls “insubstantial excuses” offered by Steel’s barrister on his behalf at a hearing to determine the length of the prison sentence. Lesley Moreland had to work for years for the chance to ask the questions *she* wanted answers to. Eventually, she did secure her meeting with Andrew Steel in prison, but when she did, she found him “more centred on feeling sorry for himself”. She relays what she thought to herself, after Steel claimed that he cried about killing Ruth every night: “you and me both, sunshine” [@morelandOrdinaryMurder2001, 191]

I found anger difficult because it felt like something *I had no right to*: as a Quaker, I felt as if I ought not to be angry, as if there was a settled and a right position, a position which involved forgiveness, or at least the ability to ‘move on’.[^4] Like these two women, I found the answer to anger was to yield, to accept that it pointed to something terribly wrong: a wrong without justice, a wrong unavenged.

I found some words from the 1987 Swarthmore Lecture, by John Lampen, very helpful. Writing about punishment, Lampen suggests that Quakers “seem to have a horror of revenge as a motive”, but says that even when revenge achieves nothing constructive, this at least is better than to make no response at all, which leaves all the hurt with the person who has been wronged. To Lampen, it is “a kind of insult” to tell people harmed by violence that they ought to be reconciled [@lampenMendingHurts1987, 53]. He suggests that in such situations, the state *should* punish, to limit the uncontrolled consequences of people acting on their own anger, however justified it might be.[^5]

So justified anger, and the demand for a response, shouldn’t be ignored. But anger doesn’t grant moral authority. It’s said in Buddhist scriptures [@oconnellwalsheDhananjaaniiSuttaDhananjaani] that the Buddha once described anger as having a “poisoned root, and a honeyed tip”. I love this image. It conveys how anger can burn us up, even as it sweetens our interactions with the world. Poison in here, sweetness out there: in the feeling that being *wronged* makes us *right*; that being *in the right* means we can *demand what we please* to redeem our losses.

Lampen’s theme, and the title of his lecture, is *Mending Hurts*. After making these claims about vengeance, he asks how the demands of justice can be met without “forging the next link in the chain of hurt” [@lampenMendingHurts1987, 53-4].

He is asking a question about moral repair. He is asking: what are we to do, when worlds have been ended? If we should punish, when should we stop? And how? And why?

These questions can be approached from two perspectives: that of people who survive serious violence, and that of people who are responsible for it. It is important to acknowledge that sometimes—often—these are in fact the same people. But I’m going to talk about them separately.

### For survivors

I think we can learn a lot from people who survive violence without having been able to rely on the state (or others) to protect them or retaliate on their behalf. In her book, *The Apology* [-@vApology2019],[^9] the playwright and activist V sets out, in the form of an imagined letter from the afterlife, the apology she waited for all her life: from her long-dead father, who abused her sexually, physically, and emotionally in childhood.

V’s father was never punished, not formally. She received only the justice she could make for herself. As is often the case for people who suffer terrible wrongs, part of V’s response found expression through her work: she has been an activist for much of her adult life, educating the public about violence against women and girls.

But this is not enough. In *The Apology*, writing as her father, V offers an unsparing account. The book is often painful to read. But her father is presented as a rounded, flawed human being, someone with a story of his own and in a hell of his own: monstrous, but not *only* a monster; miserable, proud, exploitative, entitled, reliant on scorn and violence to control others, poison both to himself and to everyone around him.

V insists that his redemption had to be earned by fully accounting for the wrongs he did—a task V’s father was not, in fact, capable of in real life. But his imagined apology, and his account of his crimes, frees her.

The etymology of the word ‘revenge’ helps us to think about this. It suggests liberation more than annihilation. We get the word from Latin: *revindicare*, derived from *vindicare* (from which we also get ‘vindicate’), among the meanings of which is to rescue, or liberate, or release from a debt, or emancipate, as in a slave.[^7] V’s concern is with escaping the burden her father forced her to carry, the burden of victimhood. For V, vengeance isn’t about destroying her father, but about unburdening herself. Knowing him as she does, she is able to use the privilege of proximity to uncover how he was not unpunished, but lived in a world defined by punishment, a world that was also of his own making.

For V, these insights were a lifetime in the making. *The Apology* took many years to appear. To recover—to make new worlds, and come to terms with loss—takes time, work, safety, and belonging. For V, unable to rely on others’ protection, recovering first meant escaping: becoming estranged from her family, away where her father could not hurt her. But getting away wasn’t enough. Like Marian Partington and Lesley Moreland, she wanted answers. They all, in some sense, wanted the people who had wronged them to explain themselves, to show that they understood the gravity of what they had done.

### For those responsible

What about the perspective of people who are responsible for harm? We’re told by politicians that punishment and imprisonment hold them accountable. What does this look like, in practice?

This is a question I’ve tried to explore through my work as an academic researcher. Does prison hold people accountable? If so, how? Does accountability always look how V imagines it—like remorse, like a person unpacking their deep responsibility for a wrongful, harmful behaviour?

I’ll try to answer this question with three more stories, drawn this time from my research interviews. I’ll describe three men who, like everyone I interviewed, were serving life sentences for murder.[^8] These three men all said they accepted their guilt. But this didn’t mean the same thing for them, not at all. And I’m going to suggest that accountability isn’t what the system is really interested in, nor what it rewards.

#### Alf

First, I’ll describe someone I’m calling Alf. Alf was convicted of murder when he was well into retirement. When I met him, he was in his eighties. Violence among people in their eighties is extremely rare. Risk assessors rated Alf’s risk of harming others in future as ‘low’, and as a result, he had a good chance of being released at a forthcoming parole hearing.

Murder was Alf’s first and his only criminal conviction. He wanted me to understand how, in the rest of his life, he had been law-abiding and conventional. Towards the end of the interview, he said:

> Do you know, I’ve been perfectly happy everywhere I’ve been in prison […] I’ve enjoyed it. It must sound silly to say that.

Alf liked and got on with prison officers, they seemed to like him, and he had held many trusted prison jobs. Generally, he got through his sentence by continuing to be who he thought he had always been: responsible, respectable, trustworthy. Although he wasn’t young, he was in good health. He had strong support from his family, who had rented out his house while he was in prison. He expected to go back home after his release, to something not totally unlike his life beforehand.

Being responsible for taking a life wasn’t really compatible with how Alf saw himself. So, I think, he sidelined and rationalised this aspect of his story. He suggested that his victim had been at least partly to blame for their death. He lowered his voice when he told me this, as if he was saying something he shouldn’t say. His attitudes hadn’t been challenged: Alf’s ‘low’ risk assessments, and the scarcity of places on rehabilitative courses meant that he hadn’t been offered a place.[^6] Put simply, he held himself accountable only in limited ways, and prison hadn’t pressured him to go deeper. Alf’s low risk seemed to be all that mattered.

#### Leon

Leon offered a very different example. Convicted in his mid-twenties, he would be well into his fifties by the earliest possible date of release. He became involved in a local street gang in his teens, and described living through the murder of a friend as a key moment in his development. From it, came an anger which propelled Leon deep into what he called “that life”. His offence was a street shooting, in which another young black man died.

Leon accepted his guilt, but pled not guilty in court: this wasn’t, he said, because he *was* innocent, but because he saw no reason to help a racist system do its job. As he saw it, violence had been a tool of the trade, and a means of survival: people in “that life” don’t rely on contracts and the courts to settle disputes. But in prison, with distance, Leon had reflected on what it had all meant. He said of himself before prison:

> My life was a mess. I was always in trouble with the police […] I was always having to look over my shoulder, paranoid if I wasn’t armed, couldn’t go anywhere […] People like to glamorise that kind of lifestyle […] [but] they know nothing about it […] You can’t go out the house, cos, you know, these gangsters are after you, trying to kill you. It’s either you or them. That’s no way to be living your life.

Leon had gotten into education in a big way, gaining a degree in prison and saying that this had opened his eyes to what could have been, how his life could have turned out differently.

*Like Alf*, Leon didn’t express deep remorse about the life he had taken. He felt remorseful, but this was centred more on his feelings about how his actions had ended up harming his family. But *unlike* Alf, Leon was ready to recognise himself as someone who used violence—and to take responsibility for doing something about this. And his attitudes towards violence *had* changeddd. *Unlike* Alf, Leon had spent time re-thinking who he was, in prison. *Unlike* Alf, he never really felt that he belonged before prison. *Like* Alf, he still had family support, but *unlike* Alf he would not be released into financial and other forms of security. So: his focus was not on showing how remorseful he was about the past, but on giving himself a better future, by finding out where he might belong after prison. As he put it, “eyes on the prize”.

He wanted to make up for lost time, and take another chance to belong. But today—I met him in 2019—he’s *still* at least a decade away from his earliest release date. Being accountable isn’t getting him anywhere—not yet.

#### Roy

The last story is Roy’s. Roy had been in prison for well over thirty years when I met him; he was sent there when I was a little boy. Heavily intoxicated, he had broken into a house to burgle it, but was surprised by the woman who lived there. Instead of leaving, Roy beat her up, then raped her, then killed her. The next day, completely unable to accept what he had done, he handed himself in to the police. He knew he would go to prison for a long time, and he believed he deserved no better.

There is an intense stigma associated with offences like this. Generally, it makes them extraordinarily difficult for the people responsible to talk about. But Roy stood out: he seemed to *want* to give an account of himself. He had spent a long time in rehabilitative courses, and could articulate a clear story linking his troubled upbringing to this capacity for violence. He linked parental neglect to a lack of self-respect, and eventually to not feeling able to care about how his actions affected others. But he was careful always to say that the fault was all his.

In other words, he was *highly* accountable: he didn’t deflect blame, and he took the responsibility upon himself. This gave him a sense of integrity and self-respect he had lacked before. As he put it:

> Without [my offence], who would I be? Where would I be? Would I have ever had a wake-up call? Would I have experienced the things I’ve experienced? […] I know it’s heinous, horrendous, horrible, all the expletives you want to throw at it. All the nasty, horrible… But even roses grow out of shit, don’t they?

Roy desperately wanted other people—me, prison staff, anyone who would listen, really—to understand how sincerely he now understood himself to be an accountable person. He wanted it known that he had really ‘gone there’ with being responsible for his offence. And he wanted to be trusted again, to live his life without supervision and to make his own mistakes. He also disagreed openly, and even argumentatively, with prison staff, about what supervision measures were necessary. This seemed to have made them mistrust him, and he had been knocked back again and again for parole. Speaking about his openness, even his argumentativeness in putting his point across, he said, “A lot of people don’t like [it]. […] They resent your inner strength, for some reason.”

### What do we learn?

Before I described these men, I described V. I suggested that for her, vengeance involved not retaliating, but escaping the sense of victimhood he had bequeathed her. I suggested that to do this, she required (at a minimum) safety, distance, and time. V, Lesley Moreland, and Marian Partington also seemed to want the person who had harmed them to recognise the gravity of their actions. Only V received this satisfaction, and only by retelling her father’s story for herself, in line with *her* needs. Lesley Moreland and Marian Partington both had to do something else with their need to forgive, because the person who had harmed them proved unable or unwilling to respond to their demands for accountability.

With Alf, Leon, and Roy, there are some interesting parallels. Our prison system—starved of the resources it requires to offer people rehabilitation—is more interested in their risk, than in the ways they are accountable. Alf wasn’t very accountable, at least not in the sense that V described it. In fact, he came close to blaming his victim. But he was assessed as low risk. He belonged before prison, he had found belonging in prison, and he expected to belong after prison. The privilege he brought with him into prison had eased his passage through the system, and made a soft landing afterwards more likely.

Leon and Roy had done more to change themselves, but they seemed to hold themselves accountable in different ways. Both of them were readier than Alf to admit their capacity for violence. Both had suffered the trauma of victimisation in the past. Roy expressed more shame, and told a story which situated responsibility deep within him. Leon told a story in which systemic racism and a lack of opportunity for people like him were the real villains.

What I think all of these men had in common with V, and Lesley Moreland, and Marian Partington, is that after the shock of terrible violence, they all needed time, and space, and distance, to make sense of what had happened to them. This sense-making, for all of them, involved storytelling: experimenting with ways to create a meaningful narrative about what happened. Finding a meaningful story, one that helps you move forward, doesn’t always mean finding the story you feel like you should have, or the story other people want to hear. The story is open-ended. It has to be.

I want these examples to undermine some of the simplistic, abstract language we’re used to using when we think about criminal justice, and about prisons. Typically, we talk about how the system is “too punitive” or “not rehabilitative enough”, as though it’s clear what that means, or as though it’s having the same kinds of effects on everyone. The reason we have these words is that systems operate according to rules, and rules require a language in which to frame decisions. The language which currently matters most, in times when the demand to punish has run ahead of the capacity to promote meaningful change, is a language centred around risk and the assessment of risk. Low risk, and you can progress with your life. High risk, and things are more complicated. But how does this help us think about what people deserve? Do Alf, and Leon, and Roy, deserve punishment, or rehabilitation?

How would you answer? Where would you even begin?

Can you see what I am getting at?

I’m saying that these concepts—risk, and punishment, and rehabilitation—are *limiting*. They are familiar, and because they are familiar we use them as if we know what we mean, and as if everyone means the same thing. Because systems become grossly unfair when they don’t operate by rules, we still *need* these words. But they are policy words, and words for specialists. They don’t help us understand human lives up close, the way they are actually lived. The common language they offer is a lowest common denominator. Up close, things are so much more individual, and these words take away so much of that individuality.

I’d like us to shift our language, to understand that these words are no more than a starting point. I want to highlight a word you might have noticed me using a few times this evening: ‘belonging’.

# Belonging

I don’t know why Usman Khan did what he did, and I don’t like to speculate.

One thing I do know—based on what I learned through the inquests—is that, like many people who leave prison, he didn’t belong. His life after release from prison sounded lonely, pointless, and hemmed in by the terms of his release licence. Day by day, he went to the gym, he went to his flat, he played computer games, he went to the library (where his internet use could be monitored), and he applied for jobs. He met with police officers and probation staff, some in more supportive roles, others tasked with surveilling him and searching his flat. He was isolated, lacking friendships, relationships, and a job. This was not a normal life.

These were extreme measures: most people released from prison after a long sentence have some licence conditions, but most are not this constraining. But anyway, they didn’t stop him doing what he did. I’m *not* saying they weren’t warranted, nor that they in any way justify his choice to do the awful things he did.

But I *am* saying: *I* wouldn’t want to live like that.

We are all human beings. Usman Khan, Alf, Leon, Roy, me, and all of you: all human beings. To live worthwhile lives, we need community, we need relationships, and we need to belong. We sometimes need boundaries, too—physical ones, like prison walls, or maybe sometimes personal and metaphorical ones, such as those created by geographical or emotional distance.

But when those boundaries are permanent, and impermeable, they are alienating. They make it easier for people to do things that are stupid, and terrible, and blameworthy.

So notwithstanding the experiences of V and other survivors of violence, notwithstanding their need for accountability, I’ve become less interested in how people are accountable. I think rehabilitation and punishment are both important.

But I am more interested in questions of belonging: who belongs? Where, when, and how do they belong? Did they always belong? Do they hope to belong in future? On what terms do they belong? And with whose support can they belong more?

I prefer to think about belonging, because I think it’s a language that’s less technical, and there’s more we can do with it, as Quakers. Thinking about belonging helps us think about community.

### Community and the gift of proximity

And Quakers *love* talking about community. The American Quaker, Parker Palmer, has written some beautiful things on the subject: about our need to be in relationship, and our need for relationships not to be too closely controlled. Palmer says, of community:

> We—especially white, middle-class folk—value community for the personal nurture it promises but ignore its challenges of political and economic justice. [@palmerPlaceCalledCommunity1977, 5]

For me, *Learning Together*, and the proximity it involved, really sharpened some of these questions. It made me think, a lot harder, about what a true community is. What it is, often, is uncomfortable: a place where unwelcome demands are made. Later in the same pamphlet, Palmer goes on:

> In a true community, we will not choose our companions, for our choices are so often limited by self-serving motives. Instead, our companions will be given to us by grace. Often they will be persons who will upset our settled view of self and world. In fact, we might define true community as the place where the person you least want to live with always lives! [@palmerPlaceCalledCommunity1977, 20][^10]

I think Palmer is getting at something quite close to the idea of proximity that I’ve been pushing forward. Reuben Miller, the Chicago prison chaplain and sociologist I mentioned at the start, wrote the following words about what he called ‘the gift of proximity’:

> Being close allows me to see things detached observers miss, and [to] move in spaces where the policy makers rarely care to look. I’ve found no easy answers; a five-point plan for policy reform can’t save us from the society we’ve made. But I have found people making lives for themselves in the wake of a conviction. We must understand their lives if we hope to bring about meaningful change. [@millerHalfwayHomeRace2021, p. loc. 4.3-4.58%]

Miller is writing about the United States, and that’s a different place to here. We have some of the same prprproblems, along with many different ones of our own.

Like Miller, I think there aren’t easy answers to the question of how we should better deal with the ‘serious cases’ I’ve been talking about this evening.

But (also like Miller) I think better answers require proximity. As Quakers, our best work in the past has come when we were close, maybe to the people and situations we least wanted to live with. Our biggest missteps, I suggested, came when we influenced and prescribed from a distance.

### How close are Quakers, now?

So: as Quakers, how close are we, now, to the realities of violence and the aftermath of violence? How close are we *willing to be*? Are we willing to really look at what becomes apparent when we are up close?

If not—if we think nice thoughts about peace and harmony in a society which tries to produce them using coercion and exclusion—then are we not, in some way, the *beneficiaries* of coercion and exclusion? What kind of voice do we *deserve to have*?

Perhaps there is work for us to do, and perhaps we can think of it as a form of peace work: to create spaces of moral repair, in which people who’ve done harm, or who have suffered harm, can belong. Perhaps our work is to experiment, and see what is possible.

If we do, we should always start with a reminder. True community—a place where *anyone* belongs—does not expose everyone to the same dangers. Those of us who have experienced violence—gang violence, gendered violence, systemic violence, state violence, any violence—might *never* feel safe in a true community. No one should be forced into communities where they cannot feel safe. We can’t *impose* true community. Maybe true community exists in pockets, not everywhere.

With that reminder in mind, we can start by asking some questions. Hopefully, these will be productive questions, not limiting ones. What would it look like for our Quaker communities, but perhaps also our wider communities, to involve more proximity, to be spaces of belonging? What would we learn? How would we be challenged? Who would we need to work with? What kinds of outreach would be required?

These are questions requiring time and thought. I’ve got some more practical ideas, but before I get onto them, here’s one last story, about belonging, and community. Not long ago, I went hill-walking with a large group of people. Among them, there were two men I hadn’t met before. One was a charismatic man with intense eyes—I’ll call him Callum. The other was quiet, reserved, a man of few words, carrying his possessions up a mountain in a blue plastic carrier bag. I’ll call him John.

As we huffed and puffed up the hill, Callum asked if I was a religious man. I said I was a Quaker. Callum shifted his tone a little, and asked me a series of questions, the kind which only want to hear certain answers. Before long, Callum asked if I knew that my Lord Jesus Christ had died and been resurrected to save me from sin? He told me the path to salvation was narrow and steep, and the path to damnation broad and easy, and he said that as the head of my household I ought to set an example to my wife and son. I am English, and a Quaker, and easily embarrassed by awkward conversations I wasn’t expecting, so I mumbled something about how complicated I find these things, and eventually, I extricated myself from the conversation.

Later, I chatted with John. He mentioned that he knew Callum from church. “Uh-oh”, I thought. “Here’s another one”. But John soon mentioned that he had been released from prison less than a year beforehand, having spent well over forty years there. I can’t adequately explain to you how difficult a transition this is—you’ll have to imagine. But the word John used for his church was “godsend”. It was the place outside prison where he felt he belonged, and as such it was the solid foundation for everything else.

Some of my sniffiness about Callum dissolved, right there and then. My theological tastes, my preference for shades of grey over certainties, and my squirming awkwardness at getting embroiled in an embarrassing conversation on a nice day out—all of this suddenly felt less important. I could see that John belonged somewhere, and I knew from the way he talked about it that this would make a difference.

# What can we do to get close?

I want to finish with a few more practical thoughts, to bring us back into the real world. I want to say more about how to get close.

For me, getting close has meant following the urge to do research, and to think, and to write. Those things in themselves haven’t made much of a difference. But they have put me close, and that has put other opportunities my way. Some years ago, I rented my flat for a while to someone recently released from a long prison sentence. This *wasn’t* altruism: I received rent. But it made a more tangible, real difference than all of my research and writing. I was able to offer one person stable accommodation and an opportunity to flourish, and they did. It built a relationship, and I *know* it made a difference because I have been close. Proximity generated an opportunity, and I recognised that owning my flat gave me a tiny slice of real power. I’d have given that power away, without even realising I had it, if I’d relied on the market to find me a tenant.

What are your tiny slices of power? For many of us, they will involve time, and attention. Quakers today are involved with the system in various ways. Perhaps you will hear about them at special interest groups this weekend: through prison chaplaincies, advocacy for prisoners with learning difficulties, volunteering as mentors or with organisations like Circles UK, which exist to create spaces of conditional, negotiated belonging for highly stigmatised people.[^11] These are all worthy causes, and it is easy to find out about them through groups such as Quakers in Criminal Justice.

But I also wonder what we can do not as individuals, but as communities. There are resources available to help us as Meetings. The Welcome Directory, for example, is an organisation which exists to help faith communities become places where people leaving prison find acceptance. Can we also be more proactive in offering our meeting houses and other properties—which are often spaces of quiet refuge—for the use of organisations who need such spaces?

Action isn’t limited to Quaker settings and Quaker spaces, either. For instance, the new prisons minister James Timpson’s company employs, as around 10% of its workforce, people who have left prison. Timpson set up a network for other employers who want to do the same to find advice and support. More opportunities of this kind are needed: not everyone in prison wants to cut keys or fix shoes. So: find out if your employer, or your university, or your organisation, offers equitable access to the 12 million people in the UK who have some form of criminal record. Push for fair hiring or admissions practices. Such actions count, and you can seek them out if you are interested in using tiny slices of power.

So you can act within and beyond Quaker spaces. But I want to finish by suggesting that, as Quakers, our tradition might give us three distinctive advantages: ideas and habits of thought which we don’t always fully realise, but which can be resources for proximity, if we remember them.

First, we’re called to ‘live adventurously’, but we are also committed to collective decision-making. We temper boldness, with discernment, and try to include different perspectives. Perhaps faith communities with more hierarchical forms of leadership might decide quickly to become spaces of belonging, of the kind Callum’s church was for John. But perhaps there are risks to moving too fast. The right path isn’t always the most urgent path. Discernment may involve listening hard to punitive or fearful attitudes within our communities, and understanding that they may be deeply and authentically held.

A second, related, advantage, is our practice of listening as a form of spirituality. For me, this was honed by sitting in Meetings for Worship over many years. But it has turned out to be a resource in the kind of research I do. How can we offer our skill in listening, and our practice of silence, to the world *beyond* our meetings? Perhaps this too might help us to get close, including by listening to people who are usually silenced and ignored because their stories are distasteful or upsetting.

Finally, there’s the idea that we ought to ‘answer that of God in everyone’. In George Fox’s writings, this phrase isn’t used to communicate the belief that everyone, deep down, is really just a nice person, trying to be good. Fox lived in what to us would seem an unimaginably rough, violent world, and he often used this phrase with a kind of prophetic urgency. In one entry in his Journal, he warned that “the mighty day of the Lord is coming upon all wickedness, ungodliness and unrighteousness”, but added that “the truth, the crown of glory, and the sceptre of righteousness over all shall be exalted; which shall answer that of God in every one upon the earth” [@amossAnsweringThatGod2011; @amossThisKnewExperimentally2023]. This is more like Callum’s language than some of us might like to think. George Fox didn’t seem to be saying that deep down, people are all just nice, and trying to be good. He was suggesting that we all have seeds of good and evil within us, but that there was a truth waiting for those who took these dual capacities seriously, and who tried to turn away from their capacity for harm. So if we try to build belonging and true community, if we advocate for these things, then we also need to practise caution. If we encounter mistrust, anger, disgust, or fear, then these emotions will sometimes be warranted. But if we are close, then we might recognise an echo of what makes us feel mistrustful, angry, disgusted, or afraid. We can use the echo to forge connections. Proximity allows us to recognise shared human experiences, and to reach out imaginatively. It reinforces belonging, by challenging us to make it.

This is creative work. It has to be done up close. It can be painful, disorientating, and difficult. But it matters.

# References

:::{refs}
:::

[^1]: People who have gone through Grendon often stand out when you meet them. While drafting the lecture my research fieldwork took me to an open prison, where a colleague and I interviewed a focus group composed of four men. Within a minute or two of the interview starting, the way one man was talking made me think, “Grendon”. And sure enough, later in the interview he mentioned that he had done part of his sentence there.
[^2]: Time is short, so if you’re interested, the pre-recorded interview with me released by Woodbrooke says more than I can say tonight, and the written version of the lecture will too.
[^3]: Unusually for someone in his position, he had a sentence in which the release date was fixed. He had originally been given an indeterminate sentence of Imprisonment for Public Protection (IPP), but this was overturned on appeal and substituted instead for a determinate sentence. As a result, Khan’s release was not decided via risk-assessment, but was automatic. He was also released directly from a maximum-security prison. This is extremely unusual, and meant that he had not made the usual series of stepped progressive moves into medium and then lower-security prisons. Were he to have undergone a more ‘normal’ release process, measures which aim to restore some freedoms in structured and monitored ways, and monitor compliance, would have kicked in. Policymakers and practitioners who gave evidence to the inquests, or who offered media punditry on the issues raised, seized on his automatic release as a major problem, since it was not decided via risk assessment. Parliament soon legislated to ensure that anyone with a terrorist conviction (and several other groups) will serve more of the sentence in prison and be subject to far more stringent release and supervision arrangements, regardless of the sentence originally imposed. Thus, one effect of Khan’s actions was to directly disadvantage many people in similar situations to himself. This example underlines how public protection arrangements can become dysfunctional if they do not offer meaningful progression or pathways to release.
[^4]: QF&P 23.103.  
[^5]: This is a fiction, of course, but a useful one. None of us has ever actually said: “I voluntarily surrender my right of retaliation to the state”. But consider what can sometimes happen when people punish *extrajudicially*: when they act on perceived wrongs privately and informally, without states playing this limiting role. We might see cliquishness, passive-aggression, or social ostracisation; we might see the rolling, chaotic cruelties of social media pile-ons; we might see the actions of a violent spouse or an abusive parent; we might see lynchings; or we might see much of the tit-for-tat violence which puts people in prison. Many of these situations can be handled far more productively through techniques such as restorative justice, but these are not always suitable where those involved do not consent to participate. Lampen is reminding us that even if we don’t necessarily want to retaliate, it’s normal to feel powerful emotions if we are wronged—anger, hatred, or disgust, for instance. It is also normal to want something to be done in response. But if everyone acts on these feelings, punishment has no end. “An eye for an eye makes the whole world blind”, Mahatma Gandhi is supposed to have said. Lampen is also reminding us, in theory, that if the state retaliates for us, then one of the useful things it’s doing is *limiting* retaliation, interrupting the relentless logic of revenge. This is a persuasive argument. But it’s also a reason we should be alarmed if it appears that the state has forgotten how to *end* punishments.
[^6]: Typically, younger, riskier men are prioritised for access to these courses, because the cost-benefit calculations are more favourable when there is more risk to be addressed in the first place.
[^7]: See *Payback* by Margaret @atwoodPayback2014 for a discussion of this. Thanks to Fergus McNeill for the recommendation.
[^8]: If you are convicted of murder, the law permits judges to impose only one punishment: a mandatory life sentence. This means you spend a minimum period of time in prison, which the law says is for punishment. A judge decides how long it will be, depending on how serious he or she finds the offence. For around 70 people, this means a ‘whole life order’, in which there is no legal possibility of release. The penalty is lifelong—almost akin to death by imprisonment. The other 8,000 or so lifers, on reaching the end of the penalty, can apply to the Parole Board for a risk-assessed release, with their decision based on a risk assessment: whether they believe it is necessary for the protection of the public to keep you in prison. If release is granted, the lifer will be supervised by probation for the rest of his or her life, and can be returned to prison if the probation staff decide public protection requires this.
[^9]: V was formerly known as Eve Ensler. Thanks to Alice Ievins for recommending the book.
[^10]: This excerpt can also be found at QF&P 10.18.
[^11]: We—British Quakers—piloted that work: we funded it, showed that it worked, and set it on its way [@qpswHTVCirclesSix2008].